name: Day 3 Multi-Step Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    env:
      AUTHOR: Fairoz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Make script executable
        run: chmod +x scripts/generate-report.sh

      - name: Run report script
        run: ./scripts/generate-report.sh

      - name: Show report contents
        run: cat report.txt

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: build-report-${{ matrix.node-version }}
          path: report.txt
