name: First Github action workflow

on: 
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: Say Hello
        run: echo "🚀 Hello, Fairoz! This is your first GitHub Actions run."
